title: Shuangyu Cai
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
pub:
  bib_extra_fields: [pdf, code, slides, video]
collections:
  blogs:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: blogs
    values:
      layout: default
